### ISSUE TITLE
Feature Request: Code Llama

### ISSUE THREAD

**Issue by forgingdestiny** [xmichaelmason/llama-docker#20]
The next gen of code llama was just released. 

https://huggingface.co/codellama/CodeLlama-70b-hf

Any future plans to support?

**Comment by xmichaelmason** [comment]
llama.cpp uses ggml models, you can either convert a hf model or grab one from hugging face. The Bloke usually gets them up quickly. 

Swapping from llama-cpp-python to transformers is one of the last things on the list to look at, tbh!

**Comment by xmichaelmason** [comment]
> The next gen of code llama was just released.
> 
> https://huggingface.co/codellama/CodeLlama-70b-hf
> 
> Any future plans to support?


I moved it up the list a little.

https://github.com/xmichaelmason/docker/tree/main/transformers

**Comment by xmichaelmason** [comment]
llama.cpp utilizes gguf models. No support required. The Bloke is pretty quick to upload gguf models to hugging face.
